//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareHub.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accreditation
    {
        public Accreditation()
        {
            this.ProviderAccreditations = new HashSet<ProviderAccreditation>();
            this.ProviderAccreditations1 = new HashSet<ProviderAccreditation>();
        }
    
        public long AccreditationId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ProviderAccreditation> ProviderAccreditations { get; set; }
        public virtual ICollection<ProviderAccreditation> ProviderAccreditations1 { get; set; }
    }
}
