//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareHub.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Localities = new HashSet<Locality>();
            this.Patients = new HashSet<Patient>();
            this.PatientQueryPayments = new HashSet<PatientQueryPayment>();
            this.Practices = new HashSet<Practice>();
        }
    
        public long CityId { get; set; }
        public int CountryId { get; set; }
        public string Name { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Locality> Localities { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
        public virtual ICollection<PatientQueryPayment> PatientQueryPayments { get; set; }
        public virtual ICollection<Practice> Practices { get; set; }
    }
}
