//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthProfileBloodPressure
    {
        public long HealthProfileBloodPressureId { get; set; }
        public string UserId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public int Systolic { get; set; }
        public int Diastolic { get; set; }
        public Nullable<int> Pulse { get; set; }
        public string Note { get; set; }
    
        public virtual User User { get; set; }
    }
}
