//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthProfileFamilyHistory
    {
        public long HealthProfileFamilyHistoryId { get; set; }
        public string UserId { get; set; }
        public string Condition { get; set; }
        public string Severity { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string HowItEnded { get; set; }
        public string Relationship { get; set; }
        public string RegionOfOrigin { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DateOfDeath { get; set; }
        public string Note { get; set; }
    
        public virtual User User { get; set; }
    }
}
