//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthProfileMedication
    {
        public long HealthProfileMedicationId { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string Strength { get; set; }
        public string Form { get; set; }
        public string Dose { get; set; }
        public string HowOftenTaken { get; set; }
        public string Reason { get; set; }
        public string Note { get; set; }
    
        public virtual User User { get; set; }
    }
}
