//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareHub.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locality
    {
        public Locality()
        {
            this.Practices = new HashSet<Practice>();
            this.ProviderLocalities = new HashSet<ProviderLocality>();
        }
    
        public long LocalityId { get; set; }
        public int CountryId { get; set; }
        public long CityId { get; set; }
        public string Name { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Practice> Practices { get; set; }
        public virtual ICollection<ProviderLocality> ProviderLocalities { get; set; }
    }
}
