//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareHub.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientQueryProvider
    {
        public long PatientQueryProviderId { get; set; }
        public long ProviderId { get; set; }
        public long PatientQueryId { get; set; }
        public string ProviderType { get; set; }
        public string ProviderTitle { get; set; }
    
        public virtual PatientQuery PatientQuery { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
