//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareHub.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientHealthTopic
    {
        public long PatientHealthTopicsId { get; set; }
        public long PatientId { get; set; }
        public string TopicName { get; set; }
        public Nullable<int> RelatedPatients { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
