//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice
    {
        public Practice()
        {
            this.ProviderPractices = new HashSet<ProviderPractice>();
            this.ProviderTimings = new HashSet<ProviderTiming>();
        }
    
        public long PracticeId { get; set; }
        public Nullable<long> PracticeTypeId { get; set; }
        public Nullable<int> BillingCurrencyId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<long> CityId { get; set; }
        public Nullable<long> LocalityId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Name { get; set; }
        public string LogoPath { get; set; }
        public string TagLine { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Landmark { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public string PrimaryPhone { get; set; }
        public string SecondaryPhone { get; set; }
        public string PrimaryEmail { get; set; }
        public string SecondaryEmail { get; set; }
        public string WebsiteAddress { get; set; }
        public Nullable<System.DateTime> DeactivatedDate { get; set; }
    
        public virtual BillingCurrency BillingCurrency { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Locality Locality { get; set; }
        public virtual PracticeType PracticeType { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<ProviderPractice> ProviderPractices { get; set; }
        public virtual ICollection<ProviderTiming> ProviderTimings { get; set; }
    }
}
