//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareHub.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderExperience
    {
        public long ProviderExperienceId { get; set; }
        public long ProviderId { get; set; }
        public string Designation { get; set; }
        public string Organization { get; set; }
        public Nullable<long> CityId { get; set; }
        public Nullable<int> StartYear { get; set; }
        public Nullable<int> EndYear { get; set; }
        public Nullable<int> TotalYears { get; set; }
    
        public virtual Provider Provider { get; set; }
    }
}
