//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareHub.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.Appointments = new HashSet<Appointment>();
            this.FavoriteProviders = new HashSet<FavoriteProvider>();
            this.PatientQueryProviders = new HashSet<PatientQueryProvider>();
            this.ProviderAccreditations = new HashSet<ProviderAccreditation>();
            this.ProviderAffiliations = new HashSet<ProviderAffiliation>();
            this.ProviderAvailabilities = new HashSet<ProviderAvailability>();
            this.ProviderAwards = new HashSet<ProviderAward>();
            this.ProviderContacts = new HashSet<ProviderContact>();
            this.ProviderEducations = new HashSet<ProviderEducation>();
            this.ProviderExperiences = new HashSet<ProviderExperience>();
            this.ProviderFees = new HashSet<ProviderFee>();
            this.ProviderInsurances = new HashSet<ProviderInsurance>();
            this.ProviderLanguages = new HashSet<ProviderLanguage>();
            this.ProviderLocalities = new HashSet<ProviderLocality>();
            this.ProviderPhotoes = new HashSet<ProviderPhoto>();
            this.ProviderPractices = new HashSet<ProviderPractice>();
            this.ProviderPremises = new HashSet<ProviderPremis>();
            this.ProviderReviews = new HashSet<ProviderReview>();
            this.ProviderServices = new HashSet<ProviderService>();
            this.ProviderSpecialties = new HashSet<ProviderSpecialty>();
            this.ProviderTreatments = new HashSet<ProviderTreatment>();
            this.ProviderVideos = new HashSet<ProviderVideo>();
            this.UserFollowDoctors = new HashSet<UserFollowDoctor>();
        }
    
        public long ProviderId { get; set; }
        public Nullable<long> ProviderTypeId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string BloodGroup { get; set; }
        public string UserId { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Description { get; set; }
        public Nullable<int> TotalExperienceYears { get; set; }
        public string TagLine { get; set; }
        public string ScreenName { get; set; }
        public int GenderId { get; set; }
        public string MobileNumber { get; set; }
        public string ExtraMobileNumber { get; set; }
        public Nullable<int> DocPoints { get; set; }
        public string TimeZone { get; set; }
        public string LicenseNumber { get; set; }
        public string LicenseCountry { get; set; }
        public string LicenseState { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public System.DateTime SignUpDate { get; set; }
        public Nullable<System.DateTime> DeactivatedDate { get; set; }
        public string StreetAddress { get; set; }
        public string RegistrationDetails { get; set; }
        public Nullable<int> RegistrationYear { get; set; }
        public Nullable<long> RegistrationCouncilId { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<FavoriteProvider> FavoriteProviders { get; set; }
        public virtual ICollection<PatientQueryProvider> PatientQueryProviders { get; set; }
        public virtual ProviderType ProviderType { get; set; }
        public virtual RegistrationCouncil RegistrationCouncil { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ProviderAccreditation> ProviderAccreditations { get; set; }
        public virtual ICollection<ProviderAffiliation> ProviderAffiliations { get; set; }
        public virtual ICollection<ProviderAvailability> ProviderAvailabilities { get; set; }
        public virtual ICollection<ProviderAward> ProviderAwards { get; set; }
        public virtual ICollection<ProviderContact> ProviderContacts { get; set; }
        public virtual ICollection<ProviderEducation> ProviderEducations { get; set; }
        public virtual ICollection<ProviderExperience> ProviderExperiences { get; set; }
        public virtual ICollection<ProviderFee> ProviderFees { get; set; }
        public virtual ICollection<ProviderInsurance> ProviderInsurances { get; set; }
        public virtual ICollection<ProviderLanguage> ProviderLanguages { get; set; }
        public virtual ICollection<ProviderLocality> ProviderLocalities { get; set; }
        public virtual ICollection<ProviderPhoto> ProviderPhotoes { get; set; }
        public virtual ICollection<ProviderPractice> ProviderPractices { get; set; }
        public virtual ICollection<ProviderPremis> ProviderPremises { get; set; }
        public virtual ICollection<ProviderReview> ProviderReviews { get; set; }
        public virtual ICollection<ProviderService> ProviderServices { get; set; }
        public virtual ICollection<ProviderSpecialty> ProviderSpecialties { get; set; }
        public virtual ICollection<ProviderTreatment> ProviderTreatments { get; set; }
        public virtual ICollection<ProviderVideo> ProviderVideos { get; set; }
        public virtual ICollection<UserFollowDoctor> UserFollowDoctors { get; set; }
    }
}
