//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareHub.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderAccreditation
    {
        public long ProviderAccreditationId { get; set; }
        public long ProviderId { get; set; }
        public long AccreditationId { get; set; }
    
        public virtual Accreditation Accreditation { get; set; }
        public virtual Accreditation Accreditation1 { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
