//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthProfileLabTest
    {
        public long HealthProfileLabTestId { get; set; }
        public string UserId { get; set; }
        public string TestName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
        public string ResultName { get; set; }
        public string ResultValue { get; set; }
        public string Unit { get; set; }
        public string Range { get; set; }
        public string Flag { get; set; }
        public string Note { get; set; }
    
        public virtual User User { get; set; }
    }
}
