//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientQuery
    {
        public PatientQuery()
        {
            this.PatientQueryFollowUps = new HashSet<PatientQueryFollowUp>();
            this.PatientQueryProviders = new HashSet<PatientQueryProvider>();
        }
    
        public long PatientQueryId { get; set; }
        public long PatientId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Summary { get; set; }
        public long SpecialtyId { get; set; }
        public Nullable<int> Age { get; set; }
        public string ScreenName { get; set; }
        public string Gender { get; set; }
        public string MedicalHistory { get; set; }
        public byte[] AttachedDocument { get; set; }
        public string DocumentName { get; set; }
        public string DocumentFormat { get; set; }
        public System.DateTime QueryCreationDateTime { get; set; }
        public string Status { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Specialty Specialty { get; set; }
        public virtual ICollection<PatientQueryFollowUp> PatientQueryFollowUps { get; set; }
        public virtual ICollection<PatientQueryProvider> PatientQueryProviders { get; set; }
    }
}
