//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderSpecialty
    {
        public long ProviderSpecialtyId { get; set; }
        public long ProviderId { get; set; }
        public long SpecialtyId { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual Specialty Specialty { get; set; }
    }
}
