//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderVideo
    {
        public long ProviderVideoId { get; set; }
        public long ProviderId { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Format { get; set; }
        public System.DateTime UploadDateTime { get; set; }
        public Nullable<System.DateTime> DeletionDateTime { get; set; }
    
        public virtual Provider Provider { get; set; }
    }
}
