//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderAffiliation
    {
        public long ProviderAffiliationId { get; set; }
        public long AffiliationId { get; set; }
        public long ProviderId { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual Affiliation Affiliation { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
