//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialty
    {
        public Specialty()
        {
            this.PatientQueries = new HashSet<PatientQuery>();
            this.ProviderSpecialties = new HashSet<ProviderSpecialty>();
        }
    
        public long SpecialtyId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<PatientQuery> PatientQueries { get; set; }
        public virtual ICollection<ProviderSpecialty> ProviderSpecialties { get; set; }
    }
}
