//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFeedback
    {
        public long UserFeedbackId { get; set; }
        public string UserId { get; set; }
        public string ScreenName { get; set; }
        public string QueryNature { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
    }
}
