//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginAudit
    {
        public long UserLoginAuditId { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public string UserId { get; set; }
        public string UserLogin { get; set; }
        public Nullable<short> LoginType { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<short> AccessStatusId { get; set; }
    
        public virtual User User { get; set; }
    }
}
