//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthProfileAllergy
    {
        public long HealthProfileAllergyId { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Reaction { get; set; }
        public Nullable<System.DateTime> FirstTimeDate { get; set; }
        public string Note { get; set; }
    
        public virtual User User { get; set; }
    }
}
