//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.HealthProfileAllergies = new HashSet<HealthProfileAllergy>();
            this.HealthProfileBloodGlucoses = new HashSet<HealthProfileBloodGlucose>();
            this.HealthProfileBloodPressures = new HashSet<HealthProfileBloodPressure>();
            this.HealthProfileCholestrols = new HashSet<HealthProfileCholestrol>();
            this.HealthProfileDiets = new HashSet<HealthProfileDiet>();
            this.HealthProfileExercises = new HashSet<HealthProfileExercise>();
            this.HealthProfileFamilyHistories = new HashSet<HealthProfileFamilyHistory>();
            this.HealthProfileHeights = new HashSet<HealthProfileHeight>();
            this.HealthProfileImmunizations = new HashSet<HealthProfileImmunization>();
            this.HealthProfileLabTests = new HashSet<HealthProfileLabTest>();
            this.HealthProfileMedicalConditions = new HashSet<HealthProfileMedicalCondition>();
            this.HealthProfileMedicalDocuments = new HashSet<HealthProfileMedicalDocument>();
            this.HealthProfileMedications = new HashSet<HealthProfileMedication>();
            this.HealthProfileProcedures = new HashSet<HealthProfileProcedure>();
            this.HealthProfileWeights = new HashSet<HealthProfileWeight>();
            this.Patients = new HashSet<Patient>();
            this.Providers = new HashSet<Provider>();
            this.UserFeedbacks = new HashSet<UserFeedback>();
            this.UserFollowDoctors = new HashSet<UserFollowDoctor>();
            this.UserFollowPatients = new HashSet<UserFollowPatient>();
            this.UserLoginAudits = new HashSet<UserLoginAudit>();
            this.UserPrefrences = new HashSet<UserPrefrence>();
        }
    
        public string UserId { get; set; }
        public string Password { get; set; }
        public int UserRoleId { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastPasswordChangeDate { get; set; }
        public Nullable<int> FailedLoginCount { get; set; }
        public Nullable<bool> Enable { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<int> SecurityQuestionId { get; set; }
        public string SecurityAnswer { get; set; }
    
        public virtual ICollection<HealthProfileAllergy> HealthProfileAllergies { get; set; }
        public virtual ICollection<HealthProfileBloodGlucose> HealthProfileBloodGlucoses { get; set; }
        public virtual ICollection<HealthProfileBloodPressure> HealthProfileBloodPressures { get; set; }
        public virtual ICollection<HealthProfileCholestrol> HealthProfileCholestrols { get; set; }
        public virtual ICollection<HealthProfileDiet> HealthProfileDiets { get; set; }
        public virtual ICollection<HealthProfileExercise> HealthProfileExercises { get; set; }
        public virtual ICollection<HealthProfileFamilyHistory> HealthProfileFamilyHistories { get; set; }
        public virtual ICollection<HealthProfileHeight> HealthProfileHeights { get; set; }
        public virtual ICollection<HealthProfileImmunization> HealthProfileImmunizations { get; set; }
        public virtual ICollection<HealthProfileLabTest> HealthProfileLabTests { get; set; }
        public virtual ICollection<HealthProfileMedicalCondition> HealthProfileMedicalConditions { get; set; }
        public virtual ICollection<HealthProfileMedicalDocument> HealthProfileMedicalDocuments { get; set; }
        public virtual ICollection<HealthProfileMedication> HealthProfileMedications { get; set; }
        public virtual ICollection<HealthProfileProcedure> HealthProfileProcedures { get; set; }
        public virtual ICollection<HealthProfileWeight> HealthProfileWeights { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
        public virtual ICollection<Provider> Providers { get; set; }
        public virtual SecurityQuestion SecurityQuestion { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual ICollection<UserFeedback> UserFeedbacks { get; set; }
        public virtual ICollection<UserFollowDoctor> UserFollowDoctors { get; set; }
        public virtual ICollection<UserFollowPatient> UserFollowPatients { get; set; }
        public virtual ICollection<UserLoginAudit> UserLoginAudits { get; set; }
        public virtual ICollection<UserPrefrence> UserPrefrences { get; set; }
    }
}
